"""Typed engineering quantities with SI-default storage, built on pint."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from engunits.base import BaseQuantity
from engunits.quantities import (
    Acceleration,
    AmountOfSubstance,
    AngularAcceleration,
    AngularVelocity,
    Area,
    Capacitance,
    Capacity,
    Charge,
    Conductance,
    Current,
    Density,
    DynamicViscosity,
    ElectricField,
    Energy,
    Force,
    Frequency,
    HeatFlux,
    Illuminance,
    Inductance,
    KinematicViscosity,
    Length,
    LuminousIntensity,
    MagneticFlux,
    MagneticFluxDensity,
    Mass,
    MassFlowRate,
    Moment,
    MomentOfInertia,
    Momentum,
    Power,
    Pressure,
    Resistance,
    SpecificHeatCapacity,
    SurfaceTension,
    Temperature,
    ThermalConductivity,
    Time,
    Velocity,
    Voltage,
    Volume,
    VolumetricFlowRate,
)
from engunits.registry import Q_, ureg

__all__ = [
    "Q_",
    "Acceleration",
    "AmountOfSubstance",
    "AngularAcceleration",
    "AngularVelocity",
    "Area",
    "BaseQuantity",
    "Capacitance",
    "Capacity",
    "Charge",
    "Conductance",
    "Current",
    "Density",
    "DynamicViscosity",
    "ElectricField",
    "Energy",
    "Force",
    "Frequency",
    "HeatFlux",
    "Illuminance",
    "Inductance",
    "KinematicViscosity",
    "Length",
    "LuminousIntensity",
    "MagneticFlux",
    "MagneticFluxDensity",
    "Mass",
    "MassFlowRate",
    "Moment",
    "MomentOfInertia",
    "Momentum",
    "Power",
    "Pressure",
    "Resistance",
    "SpecificHeatCapacity",
    "SurfaceTension",
    "Temperature",
    "ThermalConductivity",
    "Time",
    "Velocity",
    "Voltage",
    "Volume",
    "VolumetricFlowRate",
    "ureg",
]

try:
    __version__ = version("engunits")
except PackageNotFoundError:
    __version__ = "0.0.0"
