"""Shared test fixtures."""

from __future__ import annotations

from engunits.quantities import (
    Acceleration,
    AmountOfSubstance,
    AngularAcceleration,
    AngularVelocity,
    Area,
    Capacitance,
    Capacity,
    Charge,
    Conductance,
    Current,
    Density,
    DynamicViscosity,
    ElectricField,
    Energy,
    Force,
    Frequency,
    HeatFlux,
    Illuminance,
    Inductance,
    KinematicViscosity,
    Length,
    LuminousIntensity,
    MagneticFlux,
    MagneticFluxDensity,
    Mass,
    MassFlowRate,
    Moment,
    MomentOfInertia,
    Momentum,
    Power,
    Pressure,
    Resistance,
    SpecificHeatCapacity,
    SurfaceTension,
    Temperature,
    ThermalConductivity,
    Time,
    Velocity,
    Voltage,
    Volume,
    VolumetricFlowRate,
)

#: All concrete quantity classes for parametrized tests.
QUANTITY_CLASSES = [
    # SI base
    Mass,
    Length,
    Time,
    Temperature,
    Current,
    AmountOfSubstance,
    LuminousIntensity,
    # Mechanics
    Velocity,
    Acceleration,
    Force,
    Moment,
    Energy,
    Power,
    Area,
    Volume,
    Density,
    Pressure,
    Frequency,
    Momentum,
    AngularVelocity,
    AngularAcceleration,
    MomentOfInertia,
    SurfaceTension,
    # Electromagnetism
    Voltage,
    Charge,
    Capacity,
    Resistance,
    Capacitance,
    Inductance,
    MagneticFlux,
    MagneticFluxDensity,
    Conductance,
    ElectricField,
    # Fluid & Thermal
    DynamicViscosity,
    KinematicViscosity,
    MassFlowRate,
    VolumetricFlowRate,
    ThermalConductivity,
    SpecificHeatCapacity,
    HeatFlux,
    # Optics
    Illuminance,
]

#: Alternate units for testing conversion on each type.
ALT_UNITS: dict[str, str] = {
    # SI base
    "mass": "lb",
    "length": "ft",
    "time": "min",
    "temperature": "degF",
    "current": "mA",
    "amount_of_substance": "mmol",
    "luminous_intensity": "millicandela",
    # Mechanics
    "velocity": "ft/s",
    "acceleration": "ft/s**2",
    "force": "lbf",
    "moment": "lbf*ft",
    "energy": "kJ",
    "power": "hp",
    "area": "ft**2",
    "volume": "L",
    "density": "lb/ft**3",
    "pressure": "psi",
    "frequency": "kHz",
    "momentum": "lb*ft/s",
    "angular_velocity": "rpm",
    "angular_acceleration": "deg/s**2",
    "moment_of_inertia": "lb*ft**2",
    "surface_tension": "lbf/ft",
    # Electromagnetism
    "voltage": "mV",
    "charge": "mC",
    "capacity": "mA*h",
    "resistance": "kohm",
    "capacitance": "uF",
    "inductance": "mH",
    "magnetic_flux": "mWb",
    "magnetic_flux_density": "mT",
    "conductance": "mS",
    "electric_field": "V/cm",
    # Fluid & Thermal
    "dynamic_viscosity": "cP",
    "kinematic_viscosity": "cSt",
    "mass_flow_rate": "lb/s",
    "volumetric_flow_rate": "L/s",
    "thermal_conductivity": "W/(cm*K)",
    "specific_heat_capacity": "kJ/(kg*K)",
    "heat_flux": "kW/m**2",
    # Optics
    "illuminance": "klx",
}
